version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "3002:5432"
    environment:
      POSTGRES_USER: console
      POSTGRES_PASSWORD: console
      POSTGRES_DB: console
    volumes:
      - console-postgres-data:/var/lib/postgresql/data

  adminer:
    depends_on:
      - postgres
    image: adminer:latest
    restart: always
    ports:
      - "3003:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  console:
    image: europe-north1-docker.pkg.dev/nais-io/nais/images/console:main
    depends_on:
      - postgres
    volumes:
      - $HOME/.config/gcloud/application_default_credentials.json:/application_default_credentials.json
    ports:
      - "3000:3000"
    env_file:
      - .console.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /application_default_credentials.json
      CONSOLE_DATABASE_URL: postgres://console:console@postgres:5432/console?sslmode=disable
      CONSOLE_LISTEN_ADDRESS: 0.0.0.0:3000
      CONSOLE_USERSYNC_ENABLED: true
      CONSOLE_STATIC_SERVICE_ACCOUNTS: |
        [
          {
            "name": "nais-1",
            "apiKey": "key1",
            "roles": ["Team viewer", "User viewer", "Team creator", "Team member", "Admin"]
          }
        ]

volumes:
  console-postgres-data:
